/**
 * Word → sentiment valence in the range `[-5, 5]`, in the style of Finn Årup
 * Nielsen's AFINN lexicon. This is a curated subset chosen to cover common
 * product-review vocabulary rather than the full ~3,300-word list, keeping the
 * package small and dependency-free while still scoring real reviews sensibly.
 */
export const AFINN: Readonly<Record<string, number>> = {
  // strong positive
  amazing: 4,
  awesome: 4,
  excellent: 3,
  fantastic: 4,
  perfect: 3,
  outstanding: 4,
  superb: 4,
  wonderful: 4,
  brilliant: 4,
  incredible: 3,
  exceptional: 4,
  flawless: 3,
  love: 3,
  loved: 3,
  loves: 3,
  adore: 3,
  delighted: 3,
  thrilled: 4,
  exceeded: 3,
  best: 3,

  // moderate positive
  good: 3,
  great: 3,
  nice: 3,
  happy: 3,
  glad: 3,
  pleased: 3,
  satisfied: 2,
  enjoy: 2,
  enjoyed: 2,
  like: 2,
  liked: 2,
  likes: 2,
  recommend: 2,
  recommended: 2,
  quality: 2,
  reliable: 2,
  comfortable: 2,
  durable: 2,
  helpful: 2,
  impressed: 3,
  impressive: 3,
  worth: 2,
  works: 1,
  worked: 1,
  fast: 2,
  quick: 2,
  easy: 1,
  smooth: 2,
  beautiful: 3,
  pretty: 1,
  clean: 1,
  fresh: 1,
  affordable: 2,
  cheap: 1,
  bargain: 2,
  decent: 1,
  solid: 2,
  sturdy: 2,
  soft: 1,
  bright: 1,
  fine: 1,
  okay: 1,
  ok: 1,
  favorite: 2,

  // strong negative
  terrible: -3,
  horrible: -3,
  awful: -3,
  worst: -3,
  hate: -3,
  hated: -3,
  disgusting: -3,
  useless: -3,
  garbage: -3,
  atrocious: -4,
  appalling: -4,
  abysmal: -4,
  unacceptable: -3,
  scam: -4,
  fraud: -4,
  nightmare: -3,

  // moderate negative
  bad: -3,
  poor: -2,
  disappointed: -2,
  disappointing: -2,
  disappointment: -2,
  waste: -2,
  wasted: -2,
  broken: -2,
  broke: -2,
  defective: -2,
  faulty: -2,
  cheaply: -2,
  flimsy: -2,
  fragile: -1,
  inadequate: -2,
  uncomfortable: -2,
  slow: -2,
  delayed: -2,
  late: -1,
  overpriced: -2,
  expensive: -1,
  mediocre: -2,
  mismatch: -2,
  misleading: -2,
  dread: -2,
  dreaded: -2,
  annoying: -2,
  annoyed: -2,
  frustrated: -2,
  frustrating: -2,
  angry: -3,
  regret: -2,
  regrets: -2,
  fail: -2,
  failed: -2,
  fails: -2,
  failure: -2,
  problem: -2,
  problems: -2,
  issue: -1,
  issues: -1,
  complaint: -2,
  complaints: -2,
  refund: -1,
  damaged: -2,
  ripped: -2,
  stopped: -1,
  skeptical: -1,
  downhill: -2,
  cheated: -3,

  // supportive / experience words that shift sentiment in reviews
  support: 1,
  supported: 1,
  service: 1,
  resolved: 2,
  refunded: 1,
  responsive: 2,
};
